ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 6, in services_view
    client_iot = iot.FiwareIotClient('config.ini')
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/iot.py", line 26, in __init__
    super().__init__(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/__init__.py", line 27, in __init__
    config_dict = utils.read_config_file(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/utils.py", line 32, in read_config_file
    with open(config_file, 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.ini'
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 6, in services_view
    client_iot = iot.FiwareIotClient('config.ini')
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/iot.py", line 26, in __init__
    super().__init__(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/__init__.py", line 27, in __init__
    config_dict = utils.read_config_file(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/utils.py", line 32, in read_config_file
    with open(config_file, 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.ini'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 9, in services_view
    client_iot = iot.FiwareIotClient(os.path.join(BASE_DIR, 'config.ini'))
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/iot.py", line 26, in __init__
    super().__init__(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/__init__.py", line 27, in __init__
    config_dict = utils.read_config_file(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/utils.py", line 32, in read_config_file
    with open(config_file, 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/config.ini'
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 9, in services_view
    client_iot = iot.FiwareIotClient(os.path.join(BASE_DIR, 'config.ini'))
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/iot.py", line 26, in __init__
    super().__init__(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/__init__.py", line 27, in __init__
    config_dict = utils.read_config_file(config_file)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/utils.py", line 37, in read_config_file
    config_dict = {'fiware_service': config.get('service', 'fiware-service'),
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'service'
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
ERROR:django.request:Internal Server Error: /services
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/services/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
WARNING:django.security.csrf:Forbidden (CSRF cookie not set.): /services/
WARNING:django.security.csrf:Forbidden (CSRF cookie not set.): /services/
ERROR:django.request:Internal Server Error: /services
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/services/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
WARNING:django.request:Not Found: /services/
WARNING:django.request:Not Found: /entities/
ERROR:django.request:Internal Server Error: /entities/123123
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/middleware/common.py", line 63, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/middleware/common.py", line 101, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to localhost:8000/entities/123123/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
WARNING:django.request:Not Found: /entities/123123/subscriptions/
WARNING:django.request:Not Found: /entities/123123/subscriptions/asdasdasd/
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://10.7.49.163:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "STELAService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.7.49.163
ERROR:django.request:Internal Server Error: /entities/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/lucascriistiano/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102a4a668>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.7.49.163', port=1026): Max retries exceeded with url: /v2/entities?type=thing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102a4a668>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 44, in entities_view
    response_str = client_context.get_entities_by_type('thing')  # TODO Change to return from all types
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/context.py", line 64, in get_entities_by_type
    return self._send_request(url, payload, 'GET')
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/src/fiotclient/fiotclient/__init__.py", line 73, in _send_request
    r = requests.get(url, data=str_payload, headers=headers)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.7.49.163', port=1026): Max retries exceeded with url: /v2/entities?type=thing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102a4a668>: Failed to establish a new connection: [Errno 60] Operation timed out',))
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
INFO:root:Creating service
DEBUG:root:Asking to http://10.7.49.163:4041/iot/services
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "TestService",
    "Fiware-ServicePath": "/testservice",
    "Content-Type": "application/json"
}
DEBUG:root:Sending payload:
DEBUG:root:{
    "services": [
        {
            "protocol": [
                "IoTA-UL"
            ],
            "apikey": "11asd123jfakambaksdj94qwa",
            "token": "token2",
            "cbroker": "http://10.7.49.163:1026",
            "entity_type": "thing",
            "resource": "/iot/d"
        }
    ]
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 10.7.49.163
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
ERROR:django.request:Internal Server Error: /services/
Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'service_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/fiotclientgui/core/views.py", line 25, in services_view
    service_name = request.POST["service_name"]
  File "/Users/lucascriistiano/workspace/fiot-client-gui/backend/.env/lib/python3.6/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'service_name'"
WARNING:django.request:Not Found: /
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "STELAService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "",
    "Fiware-ServicePath": ""
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "",
    "Fiware-ServicePath": ""
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": ""
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": null
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": ""
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": ""
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Creating service
DEBUG:root:Asking to http://localhost:4041/iot/services
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:root:Sending payload:
DEBUG:root:{
    "services": [
        {
            "protocol": [
                "IoTA-UL"
            ],
            "apikey": "",
            "token": "token2",
            "cbroker": "http://localhost:1026",
            "entity_type": "thing",
            "resource": "/iot/d"
        }
    ]
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "POST /iot/services HTTP/1.1" 201 2
DEBUG:root:Status Code: 201
DEBUG:root:Response: 
DEBUG:root:{}
INFO:root:Creating service
DEBUG:root:Asking to http://localhost:4041/iot/services
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:root:Sending payload:
DEBUG:root:{
    "services": [
        {
            "protocol": [
                "IoTA-UL"
            ],
            "apikey": "246d9fa2a1a111e7844360f81db4b630",
            "token": "token2",
            "cbroker": "http://localhost:1026",
            "entity_type": "thing",
            "resource": "/iot/d"
        }
    ]
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "POST /iot/services HTTP/1.1" 201 2
DEBUG:root:Status Code: 201
DEBUG:root:Response: 
DEBUG:root:{}
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 2
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[]
WARNING:django.request:Not Found: /favicon.ico
INFO:root:Registering device
DEBUG:root:Asking to http://localhost:4041/iot/devices?protocol=IoTA-UL
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:root:Sending payload:
DEBUG:root:{
    "devices": [
        {
            "device_id": "STELA_DHT",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "timezone": "America/Fortaleza",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "static_attributes": [
                {
                    "name": "id",
                    "type": "string",
                    "value": "STELA_DHT"
                }
            ]
        }
    ]
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "POST /iot/devices?protocol=IoTA-UL HTTP/1.1" 201 2
DEBUG:root:Status Code: 201
DEBUG:root:Response: 
DEBUG:root:{}
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Getting entity by id 'LDR001'
DEBUG:root:Asking to http://localhost:1026/v2/entities/LDR001/attrs?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities/LDR001/attrs?type=thing HTTP/1.1" 404 95
DEBUG:root:Status Code: 404
DEBUG:root:Response: 
DEBUG:root:{
    "error": "NotFound",
    "description": "The requested entity has not been found. Check type and id"
}
INFO:root:Getting entity by id 'DHT001'
DEBUG:root:Asking to http://localhost:1026/v2/entities/DHT001/attrs?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities/DHT001/attrs?type=thing HTTP/1.1" 200 171
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "TimeInstant": {
        "type": "ISO8601",
        "value": " ",
        "metadata": {}
    },
    "humidity": {
        "type": "float",
        "value": " ",
        "metadata": {}
    },
    "temperature": {
        "type": "float",
        "value": " ",
        "metadata": {}
    }
}
INFO:root:Getting entity by id 'DHT001'
DEBUG:root:Asking to http://localhost:1026/v2/entities/DHT001/attrs?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities/DHT001/attrs?type=thing HTTP/1.1" 200 171
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "TimeInstant": {
        "type": "ISO8601",
        "value": " ",
        "metadata": {}
    },
    "humidity": {
        "type": "float",
        "value": " ",
        "metadata": {}
    },
    "temperature": {
        "type": "float",
        "value": " ",
        "metadata": {}
    }
}
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Getting entities by type '<class 'type'>'
DEBUG:root:Asking to http://localhost:1026/v2/entities?type=thing
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:1026 "GET /v2/entities?type=thing HTTP/1.1" 200 202
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:[
    {
        "id": "DHT001",
        "type": "thing",
        "TimeInstant": {
            "type": "ISO8601",
            "value": " ",
            "metadata": {}
        },
        "humidity": {
            "type": "float",
            "value": " ",
            "metadata": {}
        },
        "temperature": {
            "type": "float",
            "value": " ",
            "metadata": {}
        }
    }
]
INFO:root:Listing devices
DEBUG:root:Asking to http://localhost:4041/iot/devices
DEBUG:root:Headers:
DEBUG:root:{
    "X-Auth-Token": "NULL",
    "Fiware-Service": "StelaService",
    "Fiware-ServicePath": "/stela",
    "Content-Type": "application/json"
}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:urllib3.connectionpool:http://localhost:4041 "GET /iot/devices HTTP/1.1" 200 378
DEBUG:root:Status Code: 200
DEBUG:root:Response: 
DEBUG:root:{
    "count": 1,
    "devices": [
        {
            "device_id": "STELA_DHT",
            "service": "StelaService",
            "service_path": "/stela",
            "entity_name": "DHT001",
            "entity_type": "thing",
            "transport": "MQTT",
            "attributes": [
                {
                    "object_id": "h",
                    "name": "humidity",
                    "type": "float"
                },
                {
                    "object_id": "t",
                    "name": "temperature",
                    "type": "float"
                }
            ],
            "lazy": [],
            "commands": [],
            "static_attributes": [
                {
                    "value": "STELA_DHT",
                    "type": "string",
                    "name": "id"
                }
            ]
        }
    ]
}
